/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VolunteerRouteImport } from './routes/volunteer'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CausesRouteImport } from './routes/causes'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DonateCallbackRouteImport } from './routes/donate.callback'
import { Route as CausesSlugRouteImport } from './routes/causes.$slug'
import { Route as ApiPublicPesapalIpnRouteImport } from './routes/api/public/pesapal.ipn'

const VolunteerRoute = VolunteerRouteImport.update({
  id: '/volunteer',
  path: '/volunteer',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CausesRoute = CausesRouteImport.update({
  id: '/causes',
  path: '/causes',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateCallbackRoute = DonateCallbackRouteImport.update({
  id: '/donate/callback',
  path: '/donate/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const CausesSlugRoute = CausesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CausesRoute,
} as any)
const ApiPublicPesapalIpnRoute = ApiPublicPesapalIpnRouteImport.update({
  id: '/api/public/pesapal/ipn',
  path: '/api/public/pesapal/ipn',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/causes': typeof CausesRouteWithChildren
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/legal': typeof LegalRoute
  '/stats': typeof StatsRoute
  '/volunteer': typeof VolunteerRoute
  '/causes/$slug': typeof CausesSlugRoute
  '/donate/callback': typeof DonateCallbackRoute
  '/api/public/pesapal/ipn': typeof ApiPublicPesapalIpnRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/causes': typeof CausesRouteWithChildren
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/legal': typeof LegalRoute
  '/stats': typeof StatsRoute
  '/volunteer': typeof VolunteerRoute
  '/causes/$slug': typeof CausesSlugRoute
  '/donate/callback': typeof DonateCallbackRoute
  '/api/public/pesapal/ipn': typeof ApiPublicPesapalIpnRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/causes': typeof CausesRouteWithChildren
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/legal': typeof LegalRoute
  '/stats': typeof StatsRoute
  '/volunteer': typeof VolunteerRoute
  '/causes/$slug': typeof CausesSlugRoute
  '/donate/callback': typeof DonateCallbackRoute
  '/api/public/pesapal/ipn': typeof ApiPublicPesapalIpnRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/blog'
    | '/causes'
    | '/contact'
    | '/events'
    | '/gallery'
    | '/legal'
    | '/stats'
    | '/volunteer'
    | '/causes/$slug'
    | '/donate/callback'
    | '/api/public/pesapal/ipn'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/blog'
    | '/causes'
    | '/contact'
    | '/events'
    | '/gallery'
    | '/legal'
    | '/stats'
    | '/volunteer'
    | '/causes/$slug'
    | '/donate/callback'
    | '/api/public/pesapal/ipn'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/blog'
    | '/causes'
    | '/contact'
    | '/events'
    | '/gallery'
    | '/legal'
    | '/stats'
    | '/volunteer'
    | '/causes/$slug'
    | '/donate/callback'
    | '/api/public/pesapal/ipn'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRoute
  CausesRoute: typeof CausesRouteWithChildren
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRoute
  GalleryRoute: typeof GalleryRoute
  LegalRoute: typeof LegalRoute
  StatsRoute: typeof StatsRoute
  VolunteerRoute: typeof VolunteerRoute
  DonateCallbackRoute: typeof DonateCallbackRoute
  ApiPublicPesapalIpnRoute: typeof ApiPublicPesapalIpnRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/volunteer': {
      id: '/volunteer'
      path: '/volunteer'
      fullPath: '/volunteer'
      preLoaderRoute: typeof VolunteerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/causes': {
      id: '/causes'
      path: '/causes'
      fullPath: '/causes'
      preLoaderRoute: typeof CausesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate/callback': {
      id: '/donate/callback'
      path: '/donate/callback'
      fullPath: '/donate/callback'
      preLoaderRoute: typeof DonateCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/causes/$slug': {
      id: '/causes/$slug'
      path: '/$slug'
      fullPath: '/causes/$slug'
      preLoaderRoute: typeof CausesSlugRouteImport
      parentRoute: typeof CausesRoute
    }
    '/api/public/pesapal/ipn': {
      id: '/api/public/pesapal/ipn'
      path: '/api/public/pesapal/ipn'
      fullPath: '/api/public/pesapal/ipn'
      preLoaderRoute: typeof ApiPublicPesapalIpnRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CausesRouteChildren {
  CausesSlugRoute: typeof CausesSlugRoute
}

const CausesRouteChildren: CausesRouteChildren = {
  CausesSlugRoute: CausesSlugRoute,
}

const CausesRouteWithChildren =
  CausesRoute._addFileChildren(CausesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRoute,
  CausesRoute: CausesRouteWithChildren,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRoute,
  GalleryRoute: GalleryRoute,
  LegalRoute: LegalRoute,
  StatsRoute: StatsRoute,
  VolunteerRoute: VolunteerRoute,
  DonateCallbackRoute: DonateCallbackRoute,
  ApiPublicPesapalIpnRoute: ApiPublicPesapalIpnRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
